version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: press-kit-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: presskit
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: press-kit-api
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/presskit
      - JWT_SECRET=your_jwt_secret_for_development
      - NODE_ENV=development
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: press-kit-frontend
    restart: always
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres-data: